### ISSUE TITLE
Make cli run with python3

### ISSUE THREAD

**Issue by antony** [docker/dockercloud-cli#21]
Had to upgrade my CircleCI python version since docker-compose mysteriously broke.

Now docker-compose works fine on python 3.5.1 but docker-cloud doesn't!

I don't see any mention in the docs about python version requirements - I assume this package only runs on python2.x?

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-3.5.1/bin/docker-cloud", line 9, in <module>
    load_entry_point('docker-cloud==1.0.3', 'console_scripts', 'docker-cloud')()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/dockercloudcli/cli.py", line 10, in <module>
    from dockercloudcli import commands
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/dockercloudcli/commands.py", line 14, in <module>
    from dockercloudcli import utils
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/dockercloudcli/utils.py", line 16, in <module>
    from exceptions import BadParameter, StreamOutputError
ImportError: No module named 'exceptions'
```

**Comment by roll** [comment]
:+1:

Really needed feature..

**Comment by TAGC** [comment]
Wow, March 2017 and this is still an issue?

**Comment by glarrain** [comment]
As of 2017.04.12, in this page of the official documentation, it is implicitly stated that Python 2 and 3 are supported.
https://docs.docker.com/docker-cloud/getting-started/deploy-app/2_set_up/#install-the-docker-cloud-cli

**Comment by tifayuki** [comment]
We are currently focusing on making swarm mode GA on Docker Cloud. There will be no new features added to the existing "classic" mode of Docker Cloud, but only bugs fixing.
