### ISSUE TITLE
Hardcoded requirements versions?

### ISSUE THREAD

**Issue by roll** [docker/dockercloud-cli#7]
https://github.com/tutumcloud/cli/blob/staging/requirements.txt

If user doesn't hardcode this dependencies in dependent project any version change of six for example could break builds.

I suppose `docker-cloud` is a lib. Isn't it? 

https://caremad.io/2013/07/setup-vs-requirement/

**Comment by mcbain** [comment]
+1 

`Traceback (most recent call last):
  File "/usr/local/bin/docker-cloud", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six==1.9.0`

**Comment by satishsa1107** [comment]
+1

Traceback (most recent call last):
  File "/usr/bin/docker-cloud", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dockercloud==1.0.1' distribution was not found and is required by docker-cloud

**Comment by jcrombez** [comment]
same as satisha, the cli as a docker container is broken.

**Comment by fermayo** [comment]
@jcrombez @satishsa1107 the `dockercloud/cli` image has been rebuilt and fixed

**Comment by six8** [comment]
+1

Third party packages should be more relaxed on the version.
